### ISSUE TITLE
Test is failed

### ISSUE THREAD

**Issue by rodrigmars** [neor/Neor-Profile-SQL#2]
I'm trying to use the sqlprofiler-4.1.1 version with (MySQL Server 8.0 (64bit)) with windows 7 where I get the message:

---------------------------
Test
---------------------------
Test is failed
---------------------------
OK
---------------------------

When trying to connect to my local base.

I tried to trace some log on (windows 7) to the sqlprofiler-4.1.1 tool but to no avail.

can you help me?

**Comment by rodrigmars** [comment]
Folks

 I identified the source of the problem, the way I was authenticating the program with mysql "VERSION 8" was not compatible.

Probably the program was receiving the following notification: "Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client".

 When searching the internet(GOOGLE) I found the following command that reschowed the problem in question ...

COMMAND: ALTER USER 'root' @ 'localhost' IDENTIFIED WITH mysql_native_password BY 'password'

Folks..is necessary to put this remark in the program documentation [sqlprofiler-4.1.1] for future users do not fall into the same problem OK !!!

**Comment by marcial** [comment]
I am getting Test is failed with neor 4.1.1 and mysql 8.16
